name: Update badges
on:
  workflow_dispatch:
  # schedule: # execute everydate at 12:00 UTC
  #   - cron: "0 12 * * *"
permissions:
  actions: write
  checks: write
  contents: write
  pages: write

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: lior-dux # optional, but default will use the same from github